/* app/layout.tsx -------------------------------------------------------- */
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import PageLayout from '@/components/layout/PageLayout';
// import Parallax from '@/components/home/Parallax';   // ← uncomment if using the parallax helper

/* ─────────── Google variable fonts ─────────── */
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

/* ─────────── SEO metadata ─────────── */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/* ─────────── Root layout ─────────── */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black`}
      >
        {/* Optional hero parallax effect */}
        {/* <Parallax /> */}

        {/* Global site layout: header, footer, etc. */}
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
